### ISSUE TITLE
[Intermediate] Review handouts to make sure they are up-to-date

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/intermediate_grad_school_git_course#16]
Build and add them to the repo so that they can be downloaded from the lesson site.

**Comment by AdrianDAlessandro** [comment]
@alexdewar I noticed that there is a `make handouts` command in the makefile, which I assume makes these handouts. Maybe that can be done automatically with the pages deployment and be made available somehow?

**Comment by alexdewar** [comment]
Indeed! We will have to change over to using GitHub Actions for deployment first though. I've created an issue and assigned it to myself: #68
