### ISSUE TITLE
Discuss rebase vs merge in more detail

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/intermediate_grad_school_git_course#25]
> It could be worth illustrating the different outcomes of rebasing changes into your feature branch vs merging them in. I would usually rebase if possible to keep things "cleaner" but have sometimes merged.

> I agree it will be nice to have that comparison, but it will be rather complicated to show the result using git merge, then undo that, and then git rebase. We can just show the result and that's it, but chances are they will want to try. The repo history already shows a couple of examples of git merge, so I rather use them to illustrate the differences.

I still think seeing the concepts of rebasing and merging side-by-side is really helpful to put rebasing in context and work out the subtle differences between the two outcomes. Maybe we can signpost to this very specific article:
[Merging vs. Rebasing on Atlassian](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)

_Originally posted by @dandavies99 in https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/pull/19#pullrequestreview-1228906372_

**Comment by AdrianDAlessandro** [comment]
Add this at the end of the [Rewriting History](https://imperialcollegelondon.github.io/intermediate_grad_school_git_course/l1-03-rewriting_history/index.html) episode.
