### ISSUE TITLE
Feedback after First Delivery

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/intermediate_grad_school_git_course#32]
Overall, this went quite well! The main issue that needs to be cleaned up is consistency between episodes and the introductory course.
 - The `recipe` repo with history zip keeps the history in line, but doesn't allow for students that already have a remote (their history will not be the same as in the zip)
 - It is never said explicitly when to create the remote repo on GitHub
 - The changes to the `recipe` repo from previous episodes is not always reflected in the following episode
 - There appears to be duplication with the introductory course for the pushing and pulling section

I suggest we remove the pushing and pulling section and update the examples so that the recipe repo is consistent throughout the course.

## Day 1
1. Collaborating with Git and GitHub
	- 5 minutes
	- No questions
2. Branching and Merging
	- 45 minutes teaching
	- 5 minutes exercises
	- Ryan codes along with the material
	- Question about if we should commit a small fix directly to main (like we do with the typo)
		- The answer is "no", maybe we should adjust the example to use a branch?
	- The balance between teaching and exercises is quite lopsided here
	- The Pushing and pulling sections seems to duplicate the [same section in the introductory course](https://imperialcollegelondon.github.io/introductory_grad_school_git_course/l2-02-remote_repositories/index.html)
- Had a small break here
	- I answered some questions while Ryan paused talking for a bit
	- One student had conflicts when trying to push to his recipe repo because it conflicted with the one set up in the introductory course
	- We should confirm these two courses overlap well and do not conflict with each other
	- The Pushing and Pulling section overlaps with the intro course and assumes a remote repo has been created
3. Rewriting History
	- 17 minutes teaching
	- 20 minutes exercises
	- The reset exercise is different to the example if you have pushed to the remote in the previous exercise - makes the git graph output confusing and causes conflicts

## Day 2
4. Code versions, releases and tags
	- 20 minutes
	- We change from using `git graph` to `git log` here
	- The `recipe` repo appears to be reset in the examples (all the changes from 2 and 3 are not maintained)
	- Skipped the final exercise
5. Managing contributions to code
	- 13 minutes teaching
	- 9 minutes exercises
	- The `book-of-recipes` repo still has a `master` branch - should we change this to `main`?
	- The explanation of forking and opening a PR with that fork is here - but the group exercise where they do that is later and it doesn't perfectly align (group exercise one maintainer makes a fork - here everyone forks)
	- Pushing your tags and publishing a release requires having a remote of `recipe` - which hasn't been explicitly mentioned
- Small break here
	- One student had an issue with remote and local repos out of sync because of previous episode (for both `main` and `spicy` branches)
	- The "Configuring and Running GitHub Actions" section is a dense block of text, could be reduced or broken up with sub-headings
6. Using GitHub actions for continuous integration
	- 19 minutes teaching
	- 14 minutes exercises
	- One student didn't have "workflow" permission in his PAT - worth adding to the course
	- One student had not yet created the remote repo - worth considering why (it hasn't been strictly necessary until now)
	- Add link to our Software Engineering course in the "Run Tests" example
7. Collaborative development
	- Started 30 minutes until the end - Same as what was allocated - should allow for more?
	- Students will have already forked the repo by this point
	- Should we just add the bonus instructions in text and not just provide links?
	- Ryan was unable to add me in to any of the breakout rooms

**Comment by dc2917** [comment]
Just dumping some of my thoughts here for the moment.

Regarding bullet points 1 and 3:
- "Using GUIs and IDEs" section of introductory course asks students to add an ingredient and change an instruction, making the repository out of sync with that in recipe_with_history.zip.
- Repository in recipe_with_history.zip doesn't have a remote repository set
These two make git output code blocks inconsistent with what students will see.
 
Regarding bullet point 2:
"Branching and Merging > Multiple branches in remotes" section of intermediate course asks students to create the remote repository.

Regarding bullet point 4:
I agree that there appears to be duplication. In the intermediate course the intention is to show pushing/pulling to/from feature branches (i.e. not main), but the text in that section doesn't necessarily make this super clear, since it also provides a recap of what `push` and `pull`, making it somewhat confused. So I don't think this section should be removed, just cleaned up.

**Comment by AdrianDAlessandro** [comment]
> Regarding bullet point 2: "Branching and Merging > Multiple branches in remotes" section of intermediate course asks students to create the remote repository.

I added this as a temporary reminder to do it before we did the lesson. If that is kept depends on how we approach changing the pushing and pulling section and deal with the recipe zip file

**Comment by AdrianDAlessandro** [comment]
> * The `recipe` repo with history zip keeps the history in line, but doesn't allow for students that already have a remote (their history will not be the same as in the zip)
> * It is never said explicitly when to create the remote repo on GitHub

Add interaction to configure a remote or use existing one in the setup

> * The changes to the `recipe` repo from previous episodes is not always reflected in the following episode

Run through course to make all the changes consistent

> * There appears to be duplication with the introductory course for the pushing and pulling section

This one is more advanced - do not run through the examples when teaching it, just explain the concepts.

>    * The reset exercise is different to the example if you have pushed to the remote in the previous exercise - makes the git graph output confusing and causes conflicts

To be investigated and resolved when running through course

>    * The `recipe` repo appears to be reset in the examples (all the changes from 2 and 3 are not maintained)

Fix when running through course

>    * One student didn't have "workflow" permission in his PAT - worth adding to the course

Yes, this detail should be added

>    * Add link to our Software Engineering course in the "Run Tests" example

Yes

>    * The `book-of-recipes` repo still has a `master` branch - should we change this to `main`?

Yes, and we should add the markdownlint CI

>    * The explanation of forking and opening a PR with that fork is here (ep 5) - but the group exercise where they do that is later and it doesn't perfectly align (group exercise one maintainer makes a fork - here everyone forks)
>    * Students will have already forked the repo by this point (ep 7)

We should rework this - make the CI section before forking

**Comment by dc2917** [comment]
After re-work, some further improvements/issues have been identified:
- The output from the first `git graph` is missing `, origin/main`
- `git commit --amend` should be demonstrated with an example. This will be immediately followed by `git reset` so will not impact repo history.
- Section on stashing warrants a demonstration. Suggest walking through an example rather than an exercise.
