### ISSUE TITLE
Reference to missing "typo" in `ingredients.md`?

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/intermediate_grad_school_git_course#41]
In the text there is a reference to a typo in ingredients.md that the student is supposed to correct: https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/blob/b37cacc7501c370d5ea64ddfa5d1db32aa68ddd0/_episodes/l1-02-branching-merging.md?plain=1#L228

I couldn't see a typo in my copy of the recipe repo though (downloaded in the zip file). Have I missed something, or is there no longer a typo in there after we moved the course content around?

**Comment by TinyMarsh** [comment]
I just downloaded the zip and in `ingredients.md` the typo is "avacados". The correct spelling is "avocado". It's quite subtle and I definitely missed it the first time I went through the course. I might edit the text to make it more obvious.
