### ISSUE TITLE
Turn on pre-commit-ci

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/intermediate_grad_school_git_course#49]

**Comment by alexdewar** [comment]
I've requested access for the pre-commit.ci app, but we'll have to wait for one of the admins of the GitHub org to authorise it.

The second thing I need to do for this issue is to add a branch protection rule, but I need admin access to this repo and don't seem to have it. @dalonsoa?

**Comment by dalonsoa** [comment]
Pre commit is now activated. I don't know why it needed to be authorised by anyone, being a public repo. I'm no longer an admin and I've done it without problem.

**Comment by alexdewar** [comment]
Thanks! It's all a bit strange...

Could I still be made an admin of this particular repo, please? I'd like to set up the branch protection rules.

**Comment by dalonsoa** [comment]
I've given admin permission to the whole RSE Team, to this and the other grad school repos.
