### ISSUE TITLE
Adapt collaborating using GitHub - Clearly define Forking and Branching

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/intermediate_grad_school_git_course#5]

**Comment by dandavies99** [comment]
From the sprint planning meeting: One idea was to introduce forking as a way to specifically contribute to repositories that you don't have write access too. The majority of students will probably be working with repos for their own / their research group projects, so will not usually use a "fork-and-pull" workflow to make changes.

**Comment by dandavies99** [comment]
From the sprint planning meeting: It might be useful to briefly revisit GUIs in this section (and/or possibly in #3) in the context of visualising branches and tackling merge conflicts.

**Comment by TinyMarsh** [comment]
I've claimed this issue but I may need some help with revisiting GUIs when I get to that bit.

**Comment by TinyMarsh** [comment]
I've just realised the content that already exists in the _Collaborating with git_ section is the stuff that @cc-a pushed yesterday. Is this issue supposed to be addressing fleshing out the outline Chris created in addition to adding some things talking about forking? It's the latter that I've been working towards.
