### ISSUE TITLE
Set up live survey tool

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/intermediate_grad_school_git_course#58]
Some kind of live survey tool to keep students engaged and more easily track the progress they are making.

@cc-a Previously used Vevox for this before the course was split into two. Can you share the questions you used?

**Comment by cc-a** [comment]
1. Please choose the option that best reflects your level of experience with Git
- I use Git regularly without branches
- I use Git regularly with branches
- I use Git occasionally (when I remember)
- I haven't used Git before

 2. Belinda has downloaded a Git repository from a colleague to start her research. She runs "git log" to see the development history of the code. The most recent commit catches her eye and she uses "git show" to see what code changes were made. After mulling things over she thinks this commit has introduced a bug. She runs "git reset --hard HEAD^" to remove the most recent commit then gets on with her work developing the code. Was this a good idea?
 - Yes
 - No

3. When resolving a merge conflict which version of the code should you keep?
- The version from master (the original is always best)
- The version from my branch (I need my changes included)
- Not necessarily either

4. Pick the false statement.
- A good README file helps others find and use my code
- If I make my project private nobody can see my code except me (and people I choose)
- If I make my project public people can do whatever they want with my code
- Without a CITATION file people won't know how to cite my work

5. You have copies of the same repository on two different computers and on GitHub. You make a new branch then add some commits to the repository on computer A. What commands would you need to run to get the new branch on computer B?
- On A: "git push -u origin branch", On B: "git fetch" and "git checkout branch"
- On A: "git pull -u origin branch", On B: "git push"
- On A: "git push -u origin branch", On B: "git clone"
- On A: "git push -u origin branch", On B: "git pull -u origin branch"

**Comment by AdrianDAlessandro** [comment]
There is a draft version of this (not all text from questions can fit - needs updating)

https://www.menti.com/aleiadx398v9

**Comment by SaranjeetKaur** [comment]
It is possible to create [Polls in Teams](https://support.microsoft.com/en-gb/office/poll-attendees-during-a-teams-meeting-9923b7d4-ea97-4aa2-b8b8-b45fefe7d454) - I am testing how it goes!

**Comment by SaranjeetKaur** [comment]
It is possible to create poll drafts during the live meeting. 
- Click on "chat with participants"
- Then click on the + sign
- Click on "open app"
- Create the appropriate poll question and add the options then click on "save as draft"
- Add more questions using "new poll" button (and save them as draft) [The draft poll questions will have a "green Draft" title on them]
- Click on "Launch" to open a specific poll question for the audience [When a specific question is launched, it will have a "red Live" title on it]
- Change to "view results" to see the responses
- Once done "close the poll"
- Repeat the above to launch each question in the poll

**Comment by SaranjeetKaur** [comment]
Using breakout rooms on Teams allows you to automatically or manually add people to the selected number of rooms. Once the organiser opens the room, people are invited to them and each room also gets a dedicated Teams chat (I couldn't see it until Alex tagged me in the room chats, maybe because I created the rooms or perhaps somehow I missed seeing this room chat option on my screen)

**Comment by SaranjeetKaur** [comment]
Record the questions on the course wiki and also link to the Mentimeter (Mentimeter might be useful during the in-person course and Teams polls might be helpful when delivering online)

**Comment by SaranjeetKaur** [comment]
Comment by James: https://www.reddit.com/r/AutomateYourself/comments/12agf4g/help_automate_a_weekly_poll_in_a_teams_chat_using/ Mentions Adaptive Card Code, whatever that is (for scripted Teams chat polls)

**Comment by SaranjeetKaur** [comment]
The details above are now mentioned on the [Survey Tools wiki](https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/wiki/Survey-tools)
