### ISSUE TITLE
Revise section on multiple branches in remote

### ISSUE THREAD

**Issue by SaranjeetKaur** [ImperialCollegeLondon/intermediate_grad_school_git_course#62]
This section can probably be revised (later)

_Originally posted by @AdrianDAlessandro in https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/pull/59#discussion_r1790423413_

**Comment by AdrianDAlessandro** [comment]
Maybe shift this into its own lesson as a final step on day 1 (good to push at the end of the day)

**Comment by AdrianDAlessandro** [comment]
This should probably wait until #80 is complete since that will change the look of the git history in the repo
