### ISSUE TITLE
Change to using GitHub Actions for deployment

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/intermediate_grad_school_git_course#68]
We're currently using the legacy approach where content in the `gh-pages` branch is used for GitHub Pages. Nowadays, you can just use a GitHub Action, which has various advantages, including that you can include extra steps in your deployment.

**Comment by AdrianDAlessandro** [comment]
Will this require changing our default branch from `gh-pages` to something like `main`?

**Comment by alexdewar** [comment]
I only just noticed that this won't work because we don't have a branch called `main`... I can either change the workflow to target the `gh-pages` branch or we can make a new `main` branch. I don't mind either way, but I'm inclined to the former.

**Comment by alexdewar** [comment]
But in answer to your question, no, we should be able to leave things the same.

**Comment by alexdewar** [comment]
I thought I was commenting on the PR here. Oops.
