### ISSUE TITLE
Teach students to use `git revert` before `git reset --hard`

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/intermediate_grad_school_git_course#80]
Currently in the "rewriting history" episode we teach students the `git reset` command before `git revert`, which seems a strange way to do it. Maybe let's teach them the safe way to do things first.

**Comment by AdrianDAlessandro** [comment]
Maybe address #24 at the same time

**Comment by alexdewar** [comment]
Note that this will change the output of `git log` etc. everywhere after this, so various code boxes will need updating:

- [ ] This episode
- [ ] Tags/releases

**Comment by alexdewar** [comment]
I've been working my way through the course to build up the git history again and noticed that we already have a revert in there from the introductory course! So if students have done the intro course they should already know how to use `git revert`.

Would it be worth just signposting the relevant section in the intro course? I see two upsides:

1. Reverting commits doesn't involve rewriting history so it arguably doesn't belong in this episode anyway
2. We were thinking about dropping some content to leave longer for the collaboration exercise at the end

Thoughts?

**Comment by alexdewar** [comment]
Superseded by #91
