### ISSUE TITLE
Reformat Day 2 Episodes

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/intermediate_grad_school_git_course#82]
Some of the code blocks in the day 2 episodes are poorly formatted (not using `{: .output}` etc).

We should go through and reformat these to be consistent with day 1.

**Comment by alexdewar** [comment]
I'm not sure about this but `make lesson-check` might help with this, so maybe let's look at #72 first.

**Comment by AdrianDAlessandro** [comment]
Looks like `make lesson-check` did not help with this. So we should still do this.
