### ISSUE TITLE
Link to the setup does not work

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/intermediate_grad_school_git_course#97]
The link to the Setup page in the Overview page does not work. 

<img width="471" alt="image" src="https://github.com/user-attachments/assets/de11a40e-b7f8-47fb-9c40-eba56d51803f">

According to @AdrianDAlessandro , for this to work we need to include the `{% include links.md %}` links bit at the end. See [comment](https://github.com/ImperialCollegeLondon/grad_school_software_engineering_course/pull/51#discussion_r1820551709).

**Comment by AdrianDAlessandro** [comment]
I made that comment because that's how it was done here. But turns out `{% link setup.md %}` only resolves to `setup.html` and not the full path. We should use the link defined in `links.md`.

I've opened a PR that fixes this
